source = /home/donnie502/.config/hypr/hyprlock-colors.conf

background {
    path = /home/donnie502/.config/hypr/lockbg.jpg
    blur_passes = 3
    blur_size = 8
}

input-field {
    size = 300, 60
    outline_thickness = 3
    outer_color = $accent
    inner_color = $bg
    font_color = $fg
    check_color = $surface
    placeholder_text = Ingresa tu contraseña
    fade_on_empty = false
    position = 0, -20
    halign = center
    valign = center
}

# Reloj
label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $fg
    font_size = 90
    position = 0, 160
    halign = center
    valign = center
}

# Fecha
label {
    text = cmd[update:1000] echo "$(date +"%A, %d de %B")"
    color = $surface
    font_size = 22
    position = 0, 75
    halign = center
    valign = center
}

# Clima
label {
    text = cmd[update:1800000] echo "$(curl -s 'wttr.in/Chihuahua?format=%c+%t' 2>/dev/null)"
    color = $fg
    font_size = 20
    position = 0, 30
    halign = center
    valign = center
}

# Bateria
label {
    text = cmd[update:10000] echo "  $(cat /sys/class/power_supply/BAT0/capacity)%   -   $(cat /sys/class/power_supply/BAT0/status)"
    color = $surface
    font_size = 16
    position = 0, 40
    halign = center
    valign = bottom
}
